##small example

In [ ]:
##my equation 2x+6
import numpy as np
import pandas as pd


In [ ]:
X = np.array([8, 7, 2, 15, 40]).reshape(-1, 1)
X_1 = np.c_[np.ones((len(X), 1)), X]
X_1

array([[ 1.,  8.],
       [ 1.,  7.],
       [ 1.,  2.],
       [ 1., 15.],
       [ 1., 40.]])

In [ ]:
y = 2 * X + 6

In [ ]:
inverse_of_dot = np.linalg.inv(X_1.T.dot(X_1))
result_W = inverse_of_dot.dot(X_1.T).dot(y)
result_W

array([[6.],
       [2.]])

In [ ]:
print(f"{round(result_W[1, 0])}x + {round(result_W[0, 0])}")

2x + 6


In [ ]:
X = np.array([8, 7, 2, 15, 40])
X = np.append(X,[5,8]).reshape(-1,1)
y = np.append(y,[18,20])

In [ ]:
X_1 = np.c_[np.ones((len(X), 1)), X]

In [ ]:
inverse_of_dot = np.linalg.inv(X_1.T.dot(X_1))
result_W = inverse_of_dot.dot(X_1.T).dot(y)
result_W

array([6.0729405 , 1.99399314])

##On big data

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
for i in range(len(df)):
  if(df['Species'][i] == 'Iris-setosa' ):
    df.at[i, "class"] = -1
  else:
    df.at[i, "class"] = 1
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  class  
0       Iris-setosa   -1.0  
1       Iris-setosa   -1.0  
2       Iris-setosa   -1.0  
3       Iris-setosa   -1.0  
4       Iris-setosa   -1.0  
..              ...    ...  
145  Iris-virginica    1.0  
146  Iris-virginica    1.0  
147  Iris-virginica    1.0  
148  Iris-virginica    1.0  
149  Iris-virginica    1.0  

[150 rows x 7 columns]

In [ ]:
X = df.drop(['Species', 'class','Id'], axis=1)
Y = df[['class']].copy()

X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

Y_train.reset_index(inplace=True, drop=True)
Y_test.reset_index(inplace=True, drop=True)
X_train.reset_index(inplace=True, drop=True)
X_test.reset_index(inplace=True, drop=True)

In [ ]:
for i in range(len(X_train)):
    if Y_train['class'][i] == -1:
        X_train.loc[i] = X_train.loc[i] * -1

In [ ]:
X_train_arr = np.array(X_train)
Y_train_arr = np.array(Y_train)
Y_train_arr

array([[-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
      

In [ ]:
X_train_arr = np.c_[np.ones((len(X_train_arr), 1)), X_train_arr]
X_train_arr

array([[1. , 4.6, 3.6, 1. , 0.2],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 6.7, 3.1, 4.4, 1.4],
       [1. , 4.8, 3.4, 1.6, 0.2],
       [1. , 4.4, 3.2, 1.3, 0.2],
       [1. , 6.3, 2.5, 5. , 1.9],
       [1. , 6.4, 3.2, 4.5, 1.5],
       [1. , 5.2, 3.5, 1.5, 0.2],
       [1. , 5. , 3.6, 1.4, 0.2],
       [1. , 5.2, 4.1, 1.5, 0.1],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 6. , 3.4, 4.5, 1.6],
       [1. , 6.7, 3.1, 4.7, 1.5],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 5.5, 2.4, 3.7, 1. ],
       [1. , 6.3, 2.8, 5.1, 1.5],
       [1. , 6.4, 3.1, 5.5, 1.8],
       [1. , 6.6, 3. , 4.4, 1.4],
       [1. , 7.2, 3.6, 6.1, 2.5],
       [1. , 5.7, 2.9, 4.2, 1.3],
       [1. , 7.6, 3. , 6.6, 2.1],
       [1. , 5.6, 3. , 4.5, 1.5],
       [1. , 5.1, 3.5, 1.4, 0.2],
       [1. , 7.7, 2.8, 6.7, 2. ],
       [1. , 5.8, 2.7, 4.1, 1. ],
       [1. , 5.2, 3.4, 1.4, 0.2],
       [1. , 5. , 3.5, 1.3, 0.3],
       [1. , 5.1, 3.8, 1.9, 0.4],
       [1. , 5

In [ ]:
inverse_of_dot = np.linalg.inv(X_train_arr.T.dot(X_train_arr))
result_W = inverse_of_dot.dot(X_train_arr.T).dot(Y_train_arr)
result_W

array([[ 0.72472101],
       [-0.09046483],
       [-0.52404449],
       [ 0.42288505],
       [ 0.13539081]])

In [ ]:
X_test_arr = np.array(X_test)
X_test_arr = np.c_[np.ones((len(X_test_arr), 1)), X_test_arr]
# Y_test_arr = np.array(Y_test)

# X_test_arr

for i in range(len(X_test)):
  check = X_test_arr[i].dot(result_W)
  if(check > 0):
    Y_test.at[i, "check"] = 1
  else:
    Y_test.at[i, "check"] = -1


Y_test

class check
0     1.0     1
1    -1.0    -1
2     1.0     1
3     1.0     1
4     1.0     1
5    -1.0    -1
6     1.0     1
7     1.0     1
8     1.0     1
9     1.0     1
10    1.0     1
11   -1.0    -1
12   -1.0    -1
13   -1.0    -1
14   -1.0    -1
15    1.0     1
16    1.0     1
17    1.0     1
18    1.0     1
19    1.0     1
20   -1.0    -1
21    1.0     1
22   -1.0    -1
23    1.0     1
24    1.0     1
25    1.0     1
26    1.0     1
27    1.0     1
28   -1.0    -1
29   -1.0    -1

accuracy

In [ ]:
acc = 0
for i in range(len(Y_test)):
  if(Y_test['check'][i] == Y_test['class'][i]):
    acc+=1
acc = acc/len(Y_test) * 100
print(f"The accuracy = {acc}%")

The accuracy = 100.0%
